version: 2

# Circle jobs
jobs:

  # Ensure that the image set manifest is in place
  manifest:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npx occ 0.0.0
      - run: npm install
      - run: git clean -fxd
      - run: npx @financial-times/origami-image-set-tools build-manifest --scheme ${IMAGESET_SCHEME} --source-directory=${IMAGESET_SOURCE_DIRECTORY}
      - run:
          name: Commit and push the manifest changes
          command: >
            if [ ! "$(git status --porcelain)" == "" ]; then
              git config --global user.email "origami.support@ft.com";
              git config --global user.name "origamiserviceuser [bot]";
              git commit imageset.json -m 'Update image manifest [ci skip]';
              git push origin master;
            fi

  # Publish the image set to S3
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Publish to EU bucket
          command: npx @financial-times/origami-image-set-tools publish-s3 --bucket origami-imageset-data-eu --scheme ${IMAGESET_SCHEME} --source-directory=${IMAGESET_SOURCE_DIRECTORY} --scheme-version $CIRCLE_TAG
      - run:
          name: Publish to US bucket
          command: npx @financial-times/origami-image-set-tools publish-s3 --bucket origami-imageset-data-us --scheme ${IMAGESET_SCHEME} --source-directory=${IMAGESET_SOURCE_DIRECTORY} --scheme-version $CIRCLE_TAG
      - run: git clean -fxd
      - run: npx occ ${CIRCLE_TAG##v}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
      - run: npm publish --access public

# Circle workflows
workflows:
  version: 2
  manifest-and-publish:
    jobs:
      - manifest:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/